require("cooper.plugins-setup")
require("cooper.core.options")
require("cooper.core.keymaps")
require("cooper.core.colorscheme")
require("cooper.plugins.comment")
require("cooper.plugins.nvim-tree")
require("cooper.plugins.lualine")
require("cooper.plugins.telescope")
require("cooper.plugins.nvim-cmp")
require("cooper.plugins.lsp.mason")
require("cooper.plugins.lsp.lspsaga")
require("cooper.plugins.lsp.lspconfig")
require("cooper.plugins.lsp.null-ls")
require("cooper.plugins.autopairs")
require("cooper.plugins.treesitter")
require("cooper.plugins.gitsigns")
require("cooper.plugins.im-select")
-- require("cooper.plugins.xbase")
